#spring.application.name=job-service
server.port=8082
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


#psql
spring.datasource.url=jdbc:postgresql://localhost:5432/job?timezone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.username=lucky
spring.datasource.password=dummy
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Zipkin
management.tracing.sampling.probability=1.0
spring.config.import=configserver:http://localhost:8080